"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-11 13:03:46.743338

"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distributor_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributors'))
    )
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributors_distributor_name'), ['distributor_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_distributors_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name=op.f('fk_products_distributor_id_distributors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_teams_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)

    op.create_table('global_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(owner_user_id IS NULL) != (team_id IS NULL)', name=op.f('ck_global_sessions_ck_session_one_owner')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_global_sessions_owner_user_id_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_global_sessions_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_sessions'))
    )
    with op.batch_alter_table('global_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_sessions_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_sessions_team_id'), ['team_id'], unique=False)

    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_team_invites_created_by_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_invites_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_invites'))
    )
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invites_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_invites_id'), ['id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'user_id', name=op.f('uq_team_members_team_id'))
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('applied_ops',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['global_sessions.id'], name=op.f('fk_applied_ops_session_id_global_sessions')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_applied_ops'))
    )
    op.create_table('global_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('item_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_global_session_items_product_id_products')),
    sa.ForeignKeyConstraint(['session_id'], ['global_sessions.id'], name=op.f('fk_global_session_items_session_id_global_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_session_items'))
    )
    with op.batch_alter_table('global_session_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_session_items_id'), ['id'], unique=False)

    op.create_table('session_ops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('op_type', sa.String(length=20), nullable=False),
    sa.Column('item_uuid', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty_delta', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['global_sessions.id'], name=op.f('fk_session_ops_session_id_global_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_ops')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_session_ops_idempotency_key'))
    )
    with op.batch_alter_table('session_ops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_ops_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_ops_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_session_ops_session_id_seq', ['session_id', 'seq'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_ops', schema=None) as batch_op:
        batch_op.drop_index('ix_session_ops_session_id_seq')
        batch_op.drop_index(batch_op.f('ix_session_ops_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_ops_id'))

    op.drop_table('session_ops')
    with op.batch_alter_table('global_session_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_session_items_id'))

    op.drop_table('global_session_items')
    op.drop_table('applied_ops')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invites_id'))
        batch_op.drop_index(batch_op.f('ix_team_invites_code'))

    op.drop_table('team_invites')
    with op.batch_alter_table('global_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_sessions_team_id'))
        batch_op.drop_index(batch_op.f('ix_global_sessions_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_global_sessions_is_active'))
        batch_op.drop_index(batch_op.f('ix_global_sessions_id'))

    op.drop_table('global_sessions')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_id'))

    op.drop_table('products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributors_id'))
        batch_op.drop_index(batch_op.f('ix_distributors_distributor_name'))

    op.drop_table('distributors')
    # ### end Alembic commands ###
