"""add crash reports

Revision ID: 9819cacf8390
Revises: 9d27ab57ce58
Create Date: 2026-07-08 14:05:15.398390

"""
from alembic import op
import sqlalchemy as sa


revision = '9819cacf8390'
down_revision = '9d27ab57ce58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('android_version', sa.String(length=50), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('stacktrace', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crash_reports'))
    )
    with op.batch_alter_table('crash_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crash_reports_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crash_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crash_reports_id'))

    op.drop_table('crash_reports')
    # ### end Alembic commands ###
